---
version: '3.8'

networks:
  nginx:

services:

  nginx:
    image: abienkowski/nginx-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - target: 80
        published: 80
        protocol: http
        mode: host
    networks:
      nginx:
    
