---
version: '3.8'

networks:
  jenkins:
    external: true

volumes:
  jenkins:
    external: true

services:

  jenkins:
    image: jenkins/jenkins:2.303.3
    networks:
      jenkins:
        aliases:
          - jenkins
    ports:
      - target: 8080
        published: 8080
        protocol: http
        mode: host
    volumes:
      - jenkins:/var/jenkins_home

  agent-docker:
    image: jenkins/jnlp-agent-docker
    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_AGENT_NAME: agent-docker
      JENKINS_SECRET: 481aaad6c849766dffd41f45e23124f24ac103319001909ddc308a55809dc000
      JENKINS_TUNNEL: jenkins:50000
    networks:
      - jenkins 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
